#!/bin/sh

UPG_IMAGE=""
UPG_ACTION=""
UPG_PASSWORD=""

# Subset of OSP error codes, see core/src/lib/osp/inc/osp_upg.h for more info
OSP_UPG_IMG_FAIL=7
OSP_UPG_FL_ERASE=8
OSP_UPG_FL_WRITE=9
OSP_UPG_BC_SET=11
OSP_UPG_INTERNAL=18
OSP_UPG_INSTANCE=19



LOCKFILE="/var/lock/safeupdate.lock"
LOCK_FD=200

function upg_image_write()
{
    format_alt_overlay || exit $OSP_UPG_FL_ERASE
    bcm_flasher "$1" || exit $OSP_UPG_FL_WRITE
}

function upg_image_commit()
{
    bcm_bootstate 1 || exit $OSP_UPG_BC_SET
}

function format_alt_overlay()
{
    if readlink /dev/root | grep -q "mmcblk"; then
        # Booted from eMMC
        echo "Skip formatting eMMC overlay partition"
    else
        # Booted from NAND
        if grep -sq '"loader"' /proc/mtd; then
            # New flash layout (with the "loader" partition)
            echo "Formatting NAND overlay partition"
            format_nand_alt_overlay || {
                echo "Failed to format NAND overlay"
                return 1
            }
        else
            # Legacy flash layout
            echo "Skip format of NAND overlay partition (legacy flash layout)"
        fi
    fi
}

function format_nand_alt_overlay()
{
    # Get alternate boot partition based on the current boot partition.
    # Adapted from userspace/public/libs/bcm_flashutil/bcm_flashutil_nand.c::nandGetBootPartition()
    DEV_PREFIX="/dev/ubiblock0_"
    ROOTFS1_VOLID=4
    ROOTFS2_VOLID=6
    # Use get_rootfs_dev.sh script or fallback to reading /proc/environment/rootfs_opts
    boot_dev=$(/etc/get_rootfs_dev.sh ||
               grep -o "${DEV_PREFIX}[0-9]" /proc/environment/rootfs_opts)
    if [ "$boot_dev" = "${DEV_PREFIX}${ROOTFS1_VOLID}" ]; then
        boot_id=1
        alt_id=2
        alt_overlay_vol_id=25
    elif [ "$boot_dev" = "${DEV_PREFIX}${ROOTFS2_VOLID}" ]; then
        boot_id=2
        alt_id=1
        alt_overlay_vol_id=24
    else
        echo "Cannot detect boot partition from '$boot_dev'"
        return 1
    fi
    alt_overlay_vol_name="rootfs${alt_id}_overlay"

    # Get the size of the overlay volume in bytes
    vol_size=$(ubinfo /dev/ubi0 --vol_id=$alt_overlay_vol_id |
                grep "Size:" |                  # Size: 413 LEBs (104882176 bytes, 100.0 MiB)
                 awk -F'[()]' '{print $2}' |    # 104882176 bytes, 100.0 MiB
                  awk '{print $1}')             # 104882176
    if [ -z "$vol_size" ] || ! [ "$vol_size" -eq "$vol_size" ]; then  # Make sure vol_size is a number
        echo "Could not parse existing volume size, using default 100MiB"
        vol_size="100MiB"
    fi

    # Recreate the volume
    echo "Removing overlay volume $alt_overlay_vol_id (boot_id=$boot_id, alt_id=$alt_id)"
    ubirmvol /dev/ubi0 --vol_id=$alt_overlay_vol_id || {
        echo "Failed to remove overlay volume $alt_overlay_vol_id"
        # Fall-through to create it in any case
    }
    echo "Creating overlay volume $alt_overlay_vol_id ($alt_overlay_vol_name) with size $vol_size"
    ubimkvol /dev/ubi0 --size="$vol_size" --vol_id="$alt_overlay_vol_id" --name="$alt_overlay_vol_name" || {
        echo "Failed to create overlay volume $alt_overlay_vol_id ($alt_overlay_vol_name) with size $vol_size"
        return 1
    }
}

# Decrypt an encrypted image:

# $1 - input file
# $2 - output file
# $3 - password

# Note: This function exports the password via the environment
function upg_image_decrypt()
{
    _PASS="$3"
    export _PASS
    openssl enc -d -pass env:_PASS -nosalt -aes-256-cbc -md sha256 -in "$1" -out "$2"
    rc="$?"
    unset _PASS
    return "$rc"
}

function help()
{
    cat << EOF

safeupdate OPTIONS [-P password] [[-u|-w] IMAGE]

options are:
   -u|--upgrade [IMAGE]  - Upgrade alternate flash partition
   -w|--write [IMAGE]    - Upgrade alternate flash partition without rebooting
   -P|--password [P]     - Image decryption password

EOF
    exit 1
}

# Only one instance of safeupdate is expected to be running;
# otherwise, the results are unpredictable, and the device could be
# 'bricked'. To avoid this, a lock mechanism is implemented.
# When the lock is acquired, it will be automatically released
# when the instance terminates, so no explicit unlock call is required.
lock_instance() {
    [ ! -d "$(dirname ${LOCKFILE})" ] && mkdir -p "$(dirname ${LOCKFILE})"
    eval "exec ${LOCK_FD}>${LOCKFILE}" || { echo "Cannot open lock file."; exit ${OSP_UPG_INTERNAL}; }
    flock -n ${LOCK_FD} || { echo "Another instance of $0 is already running."; exit ${OSP_UPG_INSTANCE}; }
}


lock_instance
while [ -n "$1" ]
do
    case "$1" in
        -P|--password)
            UPG_PASSWORD="$2"
            shift 2
            ;;

        -u|--upgrade)
            UPG_IMAGE="$2"
            UPG_ACTION="u"
            shift 2
            ;;

        -w|--write)
            UPG_IMAGE="$2"
            UPG_ACTION="w"
            shift 2
            ;;

        *)
            [ -n "$1" ] && echo "Unknown option: $1"
            help
        ;;
    esac
done

[ -z "$UPG_IMAGE" -o -z "$UPG_ACTION" ] && help

if [ ! -f "$UPG_IMAGE" -o ! -r "$UPG_IMAGE" ]
then
    echo "Cannot access image file: $UPG_IMAGE"
    exit $OSP_UPG_IMG_FAIL
fi

#
# Decrypt phase; When calculating the output (unencrypted) filename, if the
# encrypted image ends in .eim, simply remove the extension.  Otherwise
# add ".img" to the output filename. A package .eospkg is decrypted to .ospkg.
#
if [ -n "$UPG_PASSWORD" ]
then
    UPG_EIM="$UPG_IMAGE"
    if [ "${UPG_EIM##*.}" == "eim" ]; then
        UPG_IMAGE="${UPG_EIM%%.eim}"
    elif [ "${UPG_EIM##*.}" == "eospkg" ]; then
        UPG_IMAGE="${UPG_EIM%%.eospkg}".ospkg
    else
        UPG_IMAGE="${UPG_EIM}.img"
    fi

    # Verify and decrypt image
    echo "Verifying image: $UPG_EIM"
    upg_image_decrypt "$UPG_EIM" "/dev/null" "$UPG_PASSWORD" || exit $OSP_UPG_IMG_FAIL
    echo "Verification OK."

    echo "Decrypting image: $UPG_EIM"
    upg_image_decrypt "$UPG_EIM" "$UPG_IMAGE" "$UPG_PASSWORD" || exit $OSP_UPG_IMG_FAIL
    echo "Decryption OK."
fi

#
# Upgrade phase
#
do_upgrade()
{
    # Check if file is a package
    if [ "${UPG_IMAGE##*.}" == "ospkg" ]; then
        echo "Upgrading using package: $UPG_IMAGE"
        ospkg install "$UPG_IMAGE" || exit $OSP_UPG_FL_WRITE
    else
        echo "Upgrading using image: $UPG_IMAGE"
        upg_image_write "$UPG_IMAGE"
        upg_image_commit
    fi
    echo "Upgrade OK"
}

case "$UPG_ACTION" in
    *u*|*w*) do_upgrade ;;
esac

#
# Reboot phase
#
case "$UPG_ACTION" in
    *u*)
        echo "Rebooting."
        reboot -Rtype=upgrade -Rreason="System upgrade"
        ;;
esac
