#!/bin/bash

# libplume.so needs to be accessible from /lib or /usr/lib
# otherwise hostTools/libcreduction complains with error:
# *** Missing 32-bit libraries: libplume.so.  Stop.

ROOTFS="$1"
mkdir -p "${ROOTFS}"/usr/lib
ln -sf ../plume/lib/libplume.so "${ROOTFS}"/usr/lib/libplume.so

