#!/bin/sh

# libopensync.so needs to be accessible from /lib or /usr/lib
# otherwise hostTools/libcreduction complains with error:
# *** Missing 32-bit libraries: libopensync.so.  Stop.
#
# Create a symlink from /usr/lib/opensync to /usr/opensync/lib

ROOTFS="$1"
DEST_LIB_DIR="/usr/lib"
[ -z "$INSTALL_PREFIX" ] && INSTALL_PREFIX="/usr/opensync"
REL_SRC_DIR="$(realpath "$INSTALL_PREFIX" --relative-to="$DEST_LIB_DIR")"
mkdir -p "$ROOTFS$DEST_LIB_DIR"
ln -sf "$REL_SRC_DIR/lib" "$ROOTFS$DEST_LIB_DIR/$(basename "$INSTALL_PREFIX")"

# healthcheck
test "$CONFIG_BCM_USE_NAS" = y || rm -vf "$ROOTFS${INSTALL_PREFIX}/scripts/healthcheck.d/"*nas*
test "$CONFIG_BCM_USE_HOSTAP" = y || rm -vf "$ROOTFS${INSTALL_PREFIX}/scripts/healthcheck.d/"*hostap*

